bump version number to 3.0.3
Bump the version number for the changes in commit 5bf7aa8d525d070b4e6d54aaa03c1cb650133253.

It was verified that commit 5bf7aa8d525d070b4e6d54aaa03c1cb650133253 also fixes an issues where, when run on macOS Sierra, qunit-mojo quits with the following error message:
```
ReferenceError: Can't find variable: QUnit

  undefined:3
  :0 in exit
  phantomjs://code/phantomjs-run-qunit9008339358566633450.js:57 in onCallback
  phantomjs://platform/webpage.js:146 in connector
  :0 in call
  :1 in callPhantom
  :9
  http://localhost:8098/qunit-mojo/qunit-1.11.0.js:1561 in runLoggingCallbacks
  http://localhost:8098/qunit-mojo/qunit-1.11.0.js:1282 in done
  http://localhost:8098/qunit-mojo/qunit-1.11.0.js:1428 in process
  http://localhost:8098/qunit-mojo/qunit-1.11.0.js:466
```